export const LOCALES = Object.freeze([
  Object.freeze({ id: "zh", code: "ZH", name: "中文", htmlLang: "zh-CN" }),
  Object.freeze({ id: "en", code: "EN", name: "English", htmlLang: "en" }),
]);

export const LANG = {
  zh: {
    nickname: "玩家",
    editNickname: "修改分享名称",
    nicknameDisclaimer: "名称仅在本机显示并用于分享文案。分享时请遵守目标平台的名称与内容规定。",
    disclaimerRead: "我已阅读并理解以上说明",
    confirm: "确认",
    cancel: "取消",
    modeNew: "NEW",
    modePro: "PRO",
    home: "返回主页",
    language: "语言",
    selectLanguage: "选择语言",
    version: "版本",
    gameStatus: "游戏状态",
    newPublish: "发布已有挑战",
    newCreate: "建立新的挑战",
    newPublishHint: "从本机挑战记录中选择并分享",
    newCreateHint: "选择游戏与时长，生成一个新局面",
    chooseGame: "选择游戏和时长",
    shareChallenge: "分享挑战",
    share: "分享",
    copy: "复制",
    copied: "已复制",
    memo: "备注",
    delete: "删除",
    deleteTitle: "删除这个挑战？",
    deleteBody: "本机记录将被删除；已经分享出去的链接仍然有效。",
    noChallenges: "本机还没有发起过挑战",
    challengeQr: "挑战链接二维码",
    invalidChallenge: "邀请码无效",
    invalidChallengeHint: "请检查邀请码，或由顶部 Logo 返回主页。",
    rules: "规则说明",
    ready: "准备",
    start: "开始",
    pause: "暂停",
    resume: "继续",
    finished: "已结束",
    settling: "结算中",
    score: "分数",
    ghost: "对手",
    time: "剩余",
    tugTied: "自己与对手平分",
    tugYouLead: "自己领先",
    tugGhostLeads: "对手领先",
    resultWin: "胜利",
    resultLose: "落败",
    resultTie: "平局",
    shareMyScore: "分享我的成绩",
    startNewChallenge: "发起新挑战",
    otherGames: "其它游戏",
    resultQr: "成绩链接二维码",
    scoreShareAfterNickname: "得",
    scoreShareAfterScore: "分在",
    inviteShareAfterNickname: "邀请你玩",
    gamePlaceholder: "游戏逻辑将在对应游戏目录中实现。",
  },
  en: {
    nickname: "Player",
    editNickname: "Edit sharing name",
    nicknameDisclaimer: "This name is stored locally and is only used in share text. Follow the naming and content rules of the platform where you post it.",
    disclaimerRead: "I have read and understand this notice",
    confirm: "Confirm",
    cancel: "Cancel",
    modeNew: "NEW",
    modePro: "PRO",
    home: "Home",
    language: "Language",
    selectLanguage: "Select language",
    version: "Version",
    gameStatus: "Game status",
    newPublish: "Share an existing challenge",
    newCreate: "Create a new challenge",
    newPublishHint: "Choose from challenges created on this device",
    newCreateHint: "Pick a game and duration to create a fresh board",
    chooseGame: "Choose a game and duration",
    shareChallenge: "Share challenge",
    share: "Share",
    copy: "Copy",
    copied: "Copied",
    memo: "Memo",
    delete: "Delete",
    deleteTitle: "Delete this challenge?",
    deleteBody: "The local record will be removed. Links already shared will keep working.",
    noChallenges: "No challenges have been created on this device yet",
    challengeQr: "Challenge link QR code",
    invalidChallenge: "Invalid invitation code",
    invalidChallengeHint: "Check the code, or use the Logo above to return home.",
    rules: "Rules",
    ready: "Ready",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    finished: "Finished",
    settling: "Settling",
    score: "Score",
    ghost: "Ghost",
    time: "Left",
    tugTied: "You and the ghost are tied",
    tugYouLead: "You are leading",
    tugGhostLeads: "The ghost is leading",
    resultWin: "You win",
    resultLose: "You lose",
    resultTie: "Tie",
    shareMyScore: "Share my score",
    startNewChallenge: "Start a new challenge",
    otherGames: "Other games",
    resultQr: "Result link QR code",
    scoreShareAfterNickname: " scored ",
    scoreShareAfterScore: " in ",
    inviteShareAfterNickname: " invites you to play ",
    gamePlaceholder: "Game logic will live in this game's own directory.",
  },
};
