export const LOCALES = Object.freeze([
  Object.freeze({ id: "zh", code: "ZH", name: "中文", htmlLang: "zh-CN" }),
  Object.freeze({ id: "en", code: "EN", name: "English", htmlLang: "en" }),
]);

export const LANG = {
  zh: {
    nickname: "玩家",
    editNickname: "修改分享名称",
    nicknameDisclaimer: "名称仅在本机显示并用于分享文案。分享时请遵守目标平台的名称与内容规定。",
    disclaimerRead: "我已阅读并理解以上说明",
    confirm: "确认",
    cancel: "取消",
    close: "关闭",
    home: "返回主页",
    language: "语言",
    selectLanguage: "选择语言",
    settings: "设置",
    gameSettings: "游戏设置",
    systemSettings: "系统设置",
    metrics: "Metrics",
    music: "音乐",
    soundEffects: "音效",
    exitCompletely: "彻底退出",
    uiStyle: "UI Style",
    duotone: "双色",
    colorful: "彩色",
    on: "开",
    off: "关",
    version: "版本",
    exit: "退出并清除本地数据",
    exitTitle: "退出并清除本地数据？",
    exitBody: "我们会尽力清除本网站下载及保存在本机的数据，然后关闭页面。这将使离线使用不可用，并可能增加下次进入网站时的加载时间。",
    exitWorking: "正在清除…",
    gameStatus: "游戏状态",
    challengesTab: "挑战",
    gamesTab: "游戏",
    createChallenge: "创建挑战",
    chooseGame: "选择游戏和时长",
    shareChallenge: "分享挑战",
    share: "分享",
    copy: "复制",
    copied: "已复制",
    createdAt: "生成时间",
    memo: "备注",
    delete: "删除",
    deleteTitle: "删除这个挑战？",
    deleteBody: "本机记录将被删除；已经分享出去的链接仍然有效。",
    noChallenges: "本机还没有发起过挑战",
    challengeQr: "挑战链接二维码",
    qrUnavailable: "二维码无法生成，请使用下方链接操作",
    play: "开始",
    invalidChallenge: "邀请码无效",
    invalidChallengeHint: "请检查邀请码，或由顶部 Logo 返回主页。",
    rules: "规则说明",
    ready: "准备",
    start: "开始",
    pause: "暂停",
    resume: "继续",
    tryAgain: "再玩一次",
    finished: "完成",
    settling: "结算",
    failed: "出错",
    gameBarTourTitle: "GameBar 指南",
    gameBarTourDone: "知道了",
    gameBarTourUnlimitedTime: "显示本局从开始起经过的时间；暂停时停止增长。",
    gameBarTourLabels: ["时间", "控制", "分数", "比分", "对手", "充能"],
    gameBarTourSteps: [
      "显示本局结束前还剩多少时间。",
      "开始后变为暂停；暂停后变为继续。",
      "显示本局当前成绩。",
      "左右长度比较你与对手的当前成绩。",
      "显示本局需要追赶的幽灵成绩。",
      "长度按0至400增长，颜色在100、200、400变化；达到400后保持满格。",
    ],
    gameError: "游戏无法继续",
    gameErrorHint: "本局没有生成成绩。请返回主页后重新开始。",
    errorCode: "错误代码",
    storageUnavailable: "本地存储不可用，本次更改可能无法保留。",
    score: "分数",
    bestScore: "最佳成绩",
    ghost: "对手",
    time: "剩余",
    elapsed: "计时",
    tugTied: "自己与对手平分",
    tugYouLead: "自己领先",
    tugGhostLeads: "对手领先",
    resultWin: "胜利",
    resultLose: "落败",
    resultTie: "平局",
    shareMyScore: "分享我的成绩",
    startNewChallenge: "发起新挑战",
    otherGames: "其它游戏",
    challengeShareAfterNickname: "发起挑战",
    challengeShareScorePrefix: "，成绩",
    challengeShareScoreSuffix: "分",
    challengeShareBeforeGame: "：",
    gamePlaceholder: "游戏逻辑将在对应游戏目录中实现。",
  },
  en: {
    nickname: "Player",
    editNickname: "Edit sharing name",
    nicknameDisclaimer: "This name is stored locally and is only used in share text. Follow the naming and content rules of the platform where you post it.",
    disclaimerRead: "I have read and understand this notice",
    confirm: "Confirm",
    cancel: "Cancel",
    close: "Close",
    home: "Home",
    language: "Language",
    selectLanguage: "Select language",
    settings: "Setting",
    gameSettings: "Game Settings",
    systemSettings: "System Settings",
    metrics: "Metrics",
    music: "Music",
    soundEffects: "Sound Effects",
    exitCompletely: "Exit completely",
    uiStyle: "UI Style",
    duotone: "Duotone",
    colorful: "Colorful",
    on: "ON",
    off: "OFF",
    version: "Version",
    exit: "Exit and clear local data",
    exitTitle: "Exit and clear local data?",
    exitBody: "We will do our best to remove this site's downloaded and locally stored data, then close the page. Offline use will stop working, and the site may take longer to load next time.",
    exitWorking: "Clearing…",
    gameStatus: "Game status",
    challengesTab: "Challenges",
    gamesTab: "Games",
    createChallenge: "Create challenge",
    chooseGame: "Choose a game and duration",
    shareChallenge: "Share challenge",
    share: "Share",
    copy: "Copy",
    copied: "Copied",
    createdAt: "Created",
    memo: "Memo",
    delete: "Delete",
    deleteTitle: "Delete this challenge?",
    deleteBody: "The local record will be removed. Links already shared will keep working.",
    noChallenges: "No challenges have been created on this device yet",
    challengeQr: "Challenge link QR code",
    qrUnavailable: "QR code unavailable. Use the link actions below.",
    play: "Play",
    invalidChallenge: "Invalid invitation code",
    invalidChallengeHint: "Check the code, or use the Logo above to return home.",
    rules: "Rules",
    ready: "Ready",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    tryAgain: "Try again",
    finished: "Done",
    settling: "Scoring",
    failed: "Error",
    gameBarTourTitle: "GameBar guide",
    gameBarTourDone: "Got it",
    gameBarTourUnlimitedTime: "Shows elapsed game time and stops advancing while paused.",
    gameBarTourLabels: ["Time", "Control", "Score", "Balance", "Ghost", "Charge"],
    gameBarTourSteps: [
      "How long remains before this game ends.",
      "Start changes to Pause, then Resume while paused.",
      "Your current result in this game.",
      "Compares your current score with the ghost score.",
      "The opponent result you are trying to catch.",
      "Length grows from 0 to 400; color changes at 100, 200, and 400, then stays full.",
    ],
    gameError: "The game cannot continue",
    gameErrorHint: "No result was created. Return home and start a new game.",
    errorCode: "Error code",
    storageUnavailable: "Local storage is unavailable. Changes may not be saved.",
    score: "Score",
    bestScore: "Best score",
    ghost: "Ghost",
    time: "Left",
    elapsed: "Elapsed",
    tugTied: "You and the ghost are tied",
    tugYouLead: "You are leading",
    tugGhostLeads: "The ghost is leading",
    resultWin: "You win",
    resultLose: "You lose",
    resultTie: "Tie",
    shareMyScore: "Share my score",
    startNewChallenge: "Start a new challenge",
    otherGames: "Other games",
    challengeShareAfterNickname: " started a challenge",
    challengeShareScorePrefix: " with a score of ",
    challengeShareScoreSuffix: "",
    challengeShareBeforeGame: ": ",
    gamePlaceholder: "Game logic will live in this game's own directory.",
  },
};
