export const GAME_LANG = {
  zh: {
    name: "贪吃蛇",
    description: "滑动引导蚂蚁队列，在逐渐加速的棋盘上寻找奖励。",
    rules: "快速四向滑动改变下一格方向；收集奖励壮大队伍，避开墙壁和自己的身体。",
    instructionsTitle: "带领蚂蚁队列",
    operationMove: "每格之间可反复修改方向，最后一次有效滑动生效。",
    operationReward: "棋盘保持三个奖励；奖励十秒后更换，最后三秒闪烁。",
    operationScore: "采集、捕食和能币分别提供1、3、5单位；能币出现在外侧两格区域。",
    board: "贪吃蛇棋盘",
    energy: "充能",
    length: "长度",
    speed: "速度",
    checkpointTitle: "继续不限时游戏？",
    checkpointCopy: "发现这场挑战尚未完成的本机断点。继续会从暂停状态恢复；新开会替换该断点。",
    checkpointContinue: "继续",
    checkpointNew: "新开",
    resultReasons: { TIME_UP: "时间结束", WALL: "撞到墙壁", BODY: "撞到身体", BOARD_FILLED: "占满棋盘" },
  },
  en: {
    name: "Snake",
    description: "Guide an ant trail through a gradually accelerating reward hunt.",
    rules: "Swipe in four directions to steer the next cell. Gather rewards to grow while avoiding walls and your own body.",
    instructionsTitle: "Lead the ant trail",
    operationMove: "Change your choice any time between cells; the latest valid swipe takes effect.",
    operationReward: "Three rewards stay active. Each refreshes after ten seconds and blinks for its final three.",
    operationScore: "Forage, prey, and energy coins give 1, 3, and 5 units. Energy coins appear in the outer two-cell band.",
    board: "Snake board",
    energy: "Energy",
    length: "Length",
    speed: "Speed",
    checkpointTitle: "Continue unlimited game?",
    checkpointCopy: "An unfinished local checkpoint exists for this challenge. Continue restores it paused; New replaces it.",
    checkpointContinue: "Continue",
    checkpointNew: "New",
    resultReasons: { TIME_UP: "Time up", WALL: "Hit the wall", BODY: "Hit the trail", BOARD_FILLED: "Board filled" },
  },
};
