export const GAME_LANG = {
  zh: {
    name: "贪吃蛇",
    description: "滑动引导蚂蚁队列，在逐渐加速的棋盘上寻找奖励。",
    rules: "快速四向滑动预设下一格或再下一格方向；收集奖励壮大队伍，避开墙壁和自己的身体。",
    instructionsTitle: "带领蚂蚁队列",
    operationMove: "每格前后半段各接受第一次有效滑动，分别控制下一格和再下一格。",
    operationReward: "棋盘保持三个奖励；奖励十秒后更换，最后三秒闪烁。",
    operationScore: "成功进入每格得1基础分并充能2；采集、捕食和能币另得10、30、50基础分。",
    board: "贪吃蛇棋盘",
    energy: "充能",
    length: "长度",
    speed: "速度",
    checkpointTitle: "继续不限时游戏？",
    checkpointCopy: "发现这场挑战尚未完成的本机断点。继续会从暂停状态恢复；新开会替换该断点。",
    checkpointContinue: "继续",
    checkpointNew: "新开",
    resultReasons: { TIME_UP: "时间结束", WALL: "撞到墙壁", BODY: "撞到身体", BOARD_FILLED: "占满棋盘" },
  },
  en: {
    name: "Snake",
    description: "Guide an ant trail through a gradually accelerating reward hunt.",
    rules: "Swipe in four directions to plan the next or following cell. Gather rewards to grow while avoiding walls and your own body.",
    instructionsTitle: "Lead the ant trail",
    operationMove: "Each cell half accepts its first valid swipe for the next or following cell.",
    operationReward: "Three rewards stay active. Each refreshes after ten seconds and blinks for its final three.",
    operationScore: "Each safe cell gives 1 base point and 2 energy; forage, prey, and coins add 10, 30, and 50 base points.",
    board: "Snake board",
    energy: "Energy",
    length: "Length",
    speed: "Speed",
    checkpointTitle: "Continue unlimited game?",
    checkpointCopy: "An unfinished local checkpoint exists for this challenge. Continue restores it paused; New replaces it.",
    checkpointContinue: "Continue",
    checkpointNew: "New",
    resultReasons: { TIME_UP: "Time up", WALL: "Hit the wall", BODY: "Hit the trail", BOARD_FILLED: "Board filled" },
  },
};
