export const GAME_LANG = {
  zh: {
    name: "叠高",
    description: "把往返移动的砖块准确落下，在限时内叠得更高。",
    rules: "点击落下移动砖块；超出虚拟承接面的包络部分会被切除，完全落空即结束。移动范围不变，承接面越窄，砖块往返越快；每层只按本次面积留存率计分。",
    instructionsTitle: "规则与操作",
    operationDrop: "点击、轻触棋盘，或按空格 / 回车落下砖块。",
    operationFootprint: "所有形状都按完整包络矩形判定；内部5×5图案只改变砖块外观。",
    operationScore: "面积留存率产生基础分并按30分充1点；本层使用落砖前能量倍率，连续快速准确落砖可维持更高倍率。",
    tower: "叠高塔场",
    drop: "落下砖块",
    layer: "层",
    shapes: {
      solid: "矩形", frame: "外框", plus: "十字", x: "X形", diamond: "菱形",
      diamondRing: "空心菱形", octagon: "八边形", star: "星形", z: "Z形", s: "S形",
    },
    energy: "连续落砖充能",
    resultReasons: { MISS: "砖块完全落空", TIME_UP: "时间到" },
    timeUp: "时间到",
    checkpointTitle: "继续不限时游戏？",
    checkpointCopy: "发现这场挑战尚未完成的本机断点。继续会从暂停状态恢复；新开会替换该断点。",
    checkpointContinue: "继续",
    checkpointNew: "新开",
  },
  en: {
    name: "Stacker",
    description: "Place moving bricks accurately and build higher before time runs out.",
    rules: "Drop the moving brick. Any envelope outside the virtual footprint is cut away; a complete miss ends the run. The travel span stays fixed while a narrower footprint makes the brick move faster; each layer scores only from its retained area.",
    instructionsTitle: "Rules & controls",
    operationDrop: "Tap the board, or press Space / Enter, to drop the brick.",
    operationFootprint: "Every shape uses its full envelope for play. Its 5×5 mask changes appearance only.",
    operationScore: "Retained area gives base points and charges 1 per 30 points. This layer uses the pre-drop energy multiplier, so quick accurate drops sustain higher multipliers.",
    tower: "Stacker tower",
    drop: "Drop brick",
    layer: "Layer",
    shapes: {
      solid: "Solid", frame: "Frame", plus: "Plus", x: "X", diamond: "Diamond",
      diamondRing: "Diamond ring", octagon: "Octagon", star: "Star", z: "Z", s: "S",
    },
    energy: "Drop streak charge",
    resultReasons: { MISS: "The brick missed completely", TIME_UP: "Time is up" },
    timeUp: "Time is up",
    checkpointTitle: "Continue unlimited game?",
    checkpointCopy: "An unfinished local checkpoint exists for this challenge. Continue restores it paused; New replaces it.",
    checkpointContinue: "Continue",
    checkpointNew: "New",
  },
};
