export const GAME_LANG = {
  zh: {
    name: "叠高",
    description: "把往返移动的砖块准确落下，在限时内叠得更高。",
    rules: "点击落下移动砖块；超出虚拟承接面的包络部分会被切除，完全落空即结束。移动范围不变，承接面越窄，砖块往返越快；每层只按本次面积留存率计分。",
    instructionsTitle: "规则与操作",
    operationDrop: "点击、轻触棋盘，或按空格 / 回车落下砖块。",
    operationFootprint: "所有形状都按完整包络矩形判定；内部5×5图案只改变砖块外观。",
    operationScore: "本层得分只由新旧footprint的面积留存率决定；层数和剩余时间不改变单层分值。",
    tower: "叠高塔场",
    drop: "落下砖块",
    layer: "层",
    shapes: {
      solid: "矩形", frame: "外框", plus: "十字", x: "X形", diamond: "菱形",
      diamondRing: "空心菱形", octagon: "八边形", star: "星形", z: "Z形", s: "S形",
    },
    energy: "叠高不使用充能",
    resultReasons: { MISS: "砖块完全落空", TIME_UP: "时间到" },
    timeUp: "时间到",
  },
  en: {
    name: "Stacker",
    description: "Place moving bricks accurately and build higher before time runs out.",
    rules: "Drop the moving brick. Any envelope outside the virtual footprint is cut away; a complete miss ends the run. The travel span stays fixed while a narrower footprint makes the brick move faster; each layer scores only from its retained area.",
    instructionsTitle: "Rules & controls",
    operationDrop: "Tap the board, or press Space / Enter, to drop the brick.",
    operationFootprint: "Every shape uses its full envelope for play. Its 5×5 mask changes appearance only.",
    operationScore: "Each layer scores only from the new-to-previous footprint area ratio; layer count and remaining time do not change its value.",
    tower: "Stacker tower",
    drop: "Drop brick",
    layer: "Layer",
    shapes: {
      solid: "Solid", frame: "Frame", plus: "Plus", x: "X", diamond: "Diamond",
      diamondRing: "Diamond ring", octagon: "Octagon", star: "Star", z: "Z", s: "S",
    },
    energy: "Stacker does not use charge",
    resultReasons: { MISS: "The brick missed completely", TIME_UP: "Time is up" },
    timeUp: "Time is up",
  },
};
