export const GAME_LANG = {
  zh: {
    name: "2048",
    description: "在方形棋盘上滑动并合并相同数字。",
    rules: "向四个方向滑动；相同数字按移动方向合并，每块砖在一次移动中最多合并一次。",
    instructionsTitle: "合并数字",
    operationMove: "快速四向滑动，或使用方向键移动全部数字。",
    operationSpawn: "每次有效移动后随机生成一块2或4；无效移动不会生成。",
    operationScore: "本次得分使用移动前充能；同时合并越多，留给下一次移动的充能越高。",
    board: "2048数字棋盘",
    energy: "充能",
    maxTile: "最大",
    moves: "步数",
    checkpointTitle: "继续不限时游戏？",
    checkpointCopy: "发现这场挑战尚未完成的本机断点。继续会从暂停状态恢复；新开会替换该断点。",
    checkpointContinue: "继续",
    checkpointNew: "新开",
    resultReasons: { TIME_UP: "时间结束", NO_MOVES: "没有可移动方向" },
  },
  en: {
    name: "2048",
    description: "Slide and merge matching numbers on a square board.",
    rules: "Swipe in four directions. Equal tiles merge in the move direction, and each tile can merge only once per move.",
    instructionsTitle: "Merge the numbers",
    operationMove: "Swipe quickly in four directions or use the arrow keys to move every tile.",
    operationSpawn: "A 2 or 4 appears after each valid move. Invalid moves spawn nothing.",
    operationScore: "Score uses energy from before the move. More simultaneous merges leave more energy for the next move.",
    board: "2048 number board",
    energy: "Energy",
    maxTile: "Max",
    moves: "Moves",
    checkpointTitle: "Continue unlimited game?",
    checkpointCopy: "An unfinished local checkpoint exists for this challenge. Continue restores it paused; New replaces it.",
    checkpointContinue: "Continue",
    checkpointNew: "New",
    resultReasons: { TIME_UP: "Time up", NO_MOVES: "No moves remaining" },
  },
};
